name: Discord EXE Download Notification

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  notify_discord_exe:
    if: github.event.release.prerelease == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get EXE download URL
        id: get_exe_url
        run: |
          EXE_URL=$(curl -s ${{ github.event.release.assets_url }} | jq -r '.[] | select(.name | endswith(".exe")) | .browser_download_url')
          echo "EXE_URL=$EXE_URL" >> $GITHUB_OUTPUT

      - name: Discord Webhook Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_EXE_WEBHOOK }}
        with:
          args: |
            Nouvelle version disponible !
            **Nom de la release:** ${{ github.event.release.name }}
            **Lien de téléchargement de l'exécutable:** ${{ steps.get_exe_url.outputs.EXE_URL }}

      - name: Debug Information
        if: failure()
        run: |
          echo "Le workflow a échoué. Informations de débogage :"
          echo "Nom de l'événement : ${{ github.event_name }}"
          echo "Nom de la release : ${{ github.event.release.name }}"
          echo "URL de la release : ${{ github.event.release.html_url }}"
          echo "URL des assets : ${{ github.event.release.assets_url }}"
