name: Discord Release Notification

on:
  release:
    types: [published]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          RELEASE_NAME="${{ github.event.release.name }}"
          RELEASE_BODY="${{ github.event.release.body }}"
          RELEASE_URL="${{ github.event.release.html_url }}"

          curl -H "Content-Type: application/json" -X POST -d '{
            "embeds": [{
              "title": "New Release: '"${RELEASE_NAME}"'",
              "description": "'"${RELEASE_BODY}"'",
              "url": "'"${RELEASE_URL}"'",
              "color": 3066993
            }]
          }' $DISCORD_WEBHOOK
