name: Discord Release Notification

on:
  release:
    types: [published]
  workflow_dispatch: # Gardé pour permettre les tests manuels

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          TITLE="New Release: ${{ github.event.release.name }}"
          DESCRIPTION=$(echo "${{ github.event.release.body }}" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
          URL="${{ github.event.release.html_url }}"

          JSON_PAYLOAD=$(cat <<EOF
          {
            "embeds": [{
              "title": "${TITLE}",
              "description": "${DESCRIPTION}",
              "url": "${URL}",
              "color": 3066993
            }]
          }
          EOF
          )

          curl -H "Content-Type: application/json" -X POST -d "${JSON_PAYLOAD}" $DISCORD_WEBHOOK
