name: Discord Release Notification

   on:
     release:
       types: [published]

   jobs:
     notify_discord:
       runs-on: ubuntu-latest
       steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Send Discord Notification
         env:
           DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
         run: |
           RELEASE_NAME=$(jq -r .release.name $GITHUB_EVENT_PATH)
           RELEASE_BODY=$(jq -r .release.body $GITHUB_EVENT_PATH)
           RELEASE_URL=$(jq -r .release.html_url $GITHUB_EVENT_PATH)
           
           curl -H "Content-Type: application/json" -X POST -d '{
             "embeds": [{
               "title": "New Release: '"$RELEASE_NAME"'",
               "description": "'"${RELEASE_BODY//$'\n'/\\n}"'",
               "url": "'"$RELEASE_URL"'",
               "color": 3066993
             }]
           }' $DISCORD_WEBHOOK